version: "3.4"
   
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: on-failure
  app:
    build: ./web
    command: sh -c "python manage.py collectstatic --no-input && yes | python manage.py makemigrations test && python manage.py migrate && gunicorn main.wsgi -b 0.0.0.0:8000 --reload --enable-stdio-inheritance"
    #python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    #container_name: app
    volumes:
      - ./web/:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    #hostname: app
    image: app-image
    restart: on-failure

