# Generated by Django 2.2.16 on 2020-10-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=255, verbose_name='возраст, год'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(verbose_name='вес, кг'),
        ),
    ]
