# Generated by Django 2.2.16 on 2020-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_auto_20201031_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='aviary',
            field=models.IntegerField(null=True, verbose_name='Вольер №'),
        ),
    ]
